name = "HugoTeX"
license = "MIT"
licenselink = "https://github.com/HelloRusk/HugoTeX/blob/master/LICENSE"
description = "LaTeX style hugo theme"
homepage = "https://hugotex.netlify.app/"
tags = ["blog", "minimal", "simple", "LaTeX"]
features = ["minimal", "simple", "responsive", "syntax highlight", "LaTeX"]
min_version = "0.60.1"

[author]
  name = "HelloRusk"
  homepage = "https://hellorusk.net"