baseURL = "https://hugotex.vercel.app/"
title = "HugoTeX"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[pagination]
  pagerSize = 3

[Params.author]
  name = "Kaito Sugimoto"
  abstract = """
  I'm a software engineer and a coffee enthusiast in Japan.
  My primary interest lies in the area of natural language processing.
  """

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "paraiso-dark"

[Params]
  darkmode = true
